---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "ankara-cp3"
  namespace: "ankara-cp"
spec:
  baseDomain: "odine.com"
  clusterImageSetNameRef: "cluster-image-001"
  sshPublicKey: "ssh-rsa dsfgsfgsdfgdfgdfgd"
  pullSecretRef:
    name: "/secret/refernce0"
  clusters:
  - clusterName: "ankara-cp3"
    extraManifestPath: "/clusters/manifests"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "treterte.yaml"
        - "esgfest.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      location: "ankara"
      test: "test"
    clusterNetwork:
    - cidr: "192.168.1.0/24"
      hostPrefix: 24
    machineNetwork:
    - cidr: "192.168.1.0/24"
    apiVIP: "192.168.1.0"
    ingressVIP: "192.168.1.0"
    serviceNetwork:
    - "192.168.1.0/24"
    additionalNTPSources:
    - "192.168.1.0"
    - "ntp.pool.org"
    nodes:
    - hostName: "bst-bitbucket.odine.tech"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels:
        openshift: "test"
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        vendor: "Intel"
        deviceName: "/dev/sda"
        size: 190
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "active-backup"
              port:
              - "ens1f0: 04:32:01:52:74:70"
              - "ens2f0: C4:CB:E1:B5:89:01"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "bond0"
            description: "bond for data"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 400
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.0"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.400"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "bond0.400"
              destination: "0.0.0.0/0"
              next-hop-address: "192.168.1.0"
    - hostName: "bst-bitbucket.odine.tech"
      role: "worker"
      bmcAddress: "172.16.180.17"
      bmcCredentialsName:
        name: "bmc-credentials-1"
      nodeLabels: {}
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/sdb"
        size: 100
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens3f0"
          macAddress: "90:5e:d9:00:0c:d0"
        - name: "ens3f1"
          macAddress: "90:5e:d9:00:0c:d2"
        - name: "ens4f0"
          macAddress: "9c:69:b4:65:6d:78"
        - name: "ens4f1"
          macAddress: "9c:69:b4:65:6d:79"
        - name: "ens4f2"
          macAddress: "9c:69:b4:65:6d:7a"
        - name: "ens4f3"
          macAddress: "9c:69:b4:65:6d:7b"
        - name: "ens5f0"
          macAddress: "90:c7:10:01:67:5f"
        - name: "ens5f1"
          macAddress: "90:c7:10:01:67:60"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens3f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens3f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f2"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f3"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens5f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens5f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "broadcast"
              port:
              - "ens4f1: 9c:69:b4:65:6d:79"
              - "ens5f1: 90:c7:10:01:67:60"
              - "ens5f0: 90:c7:10:01:67:5f"
              - "ens3f1: 90:5e:d9:00:0c:d2"
              - "ens3f8: 90:5e:d9:00:0c:d2"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "bond1"
            description: "bond for transfer"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond1"
              id: 0
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond1.0"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: ""
              destination: "0.0.0.0/0"
              next-hop-address: ""