---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "ahmet-2"
  namespace: "ahmet-namespace-2"
spec:
  baseDomain: "odine.com"
  clusterImageSetNameRef: "asdasfsdfdsgdfgfdg"
  sshPublicKey: "4g45456546456"
  pullSecretRef:
    name: "dsffdsfsd/asdasda.txt"
  clusters:
  - clusterName: "ahmet-cluster-2"
    extraManifestPath: "manifests/cluster.yaml"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "manifestsasdsafasfs/cluster.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      location: "Ankara"
    clusterNetwork:
    - cidr: "192.168.1.0/24"
      hostPrefix: 24
    machineNetwork:
    - cidr: "192.168.1.1/24"
    apiVIP: "10.10.10.11"
    ingressVIP: "10.10.10.10"
    serviceNetwork: []
    additionalNTPSources: []
    nodes:
    - hostName: "sadsafsdfds"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels: {}
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "Unknown"
        deviceName: ""
        size: 0
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          dns-resolver:
            config:
              server: []
          routes:
            config:
            - next-hop-interface: ""
              destination: "0.0.0.0/0"
              next-hop-address: ""